### ISSUE TITLE
ngx_brotli + nginx SSI

### ISSUE THREAD

**Issue by centminmod** [google/ngx_brotli#8] opened 2015-11-10 14:45 UTC
Not sure if it's related but in Firefox 45 nightly browser with Nginx compiled with ngx_brotli support, all my nginx SSI include text and html files have not loaded over https HTTP/2 on my site at https://centminmod.com/ ?

i.e. SSI include files are used for nav menu and sidebar links https://centminmod.com/news.html they all show up in Chrome 46, Opera 33 but **not** in Firefox 45 nightly or Firefox 44 dev editions ?

my Nginx configuration

nginx -V
nginx version: nginx/1.9.6
built by clang 3.4.2 (tags/RELEASE_34/dot2-final)
built with LibreSSL 2.2.4
TLS SNI support enabled
configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream --with-stream_ssl_module --with-http_gzip_static_module --add-module=../ngx_brotli --add-module=../ngx_pagespeed-release-1.9.32.10-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module --with-http_geoip_module --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-ngx-fancyindex --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../lua-nginx-module-0.9.16 --add-module=../lua-upstream-nginx-module-0.03 --add-module=../lua-upstream-cache-nginx-module-0.1.1 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.261 --with-pcre=../pcre-8.37 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.2.4

settings

    brotli on;
    brotli_static on;
    brotli_min_length 1000;
    brotli_buffers 32 8k;
    brotli_comp_level 5;
    brotli_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;

**Comment by PiotrSikora** [comment] 2015-11-11 22:20
Thanks for another bug report! :)

Unfortunately, the root cause is the same as in case of https://github.com/pagespeed/ngx_pagespeed/issues/1021, that is, there is no nginx-approved way of injecting 3rd-party filters at arbitrary positions in the chain and when using the only nginx-approved way (i.e. `HTTP_AUX_FILTER_MODULES`), Brotli filter runs _before_ SSI, which means that SSI filter sees compressed data, which it cannot parse.

I'll look into this, hopefully later today, but the reality is that the hacky way of injecting filters right before gzip filter is going to conflict with other 3rd party modules... :(

**Comment by centminmod** [comment] 2015-11-12 02:22
thanks @PiotrSikora indeed problematic

hope you and/or someone can work their magic as ngx_brotli is very promising as nothing beats faster page load times than smaller file sizes :)

**Comment by PiotrSikora** [comment] 2015-11-14 01:35
Fixed in 019c0ee2356e10f5209266b457a3596360108a16.

**Closed by PiotrSikora** 2015-11-14 01:35 UTC

**Comment by centminmod** [comment] 2015-11-14 15:02
sweet thanks @PiotrSikora !

**Comment by centminmod** [comment] 2015-11-17 18:33
@PiotrSikora just chiming in to confirm it's fixed on my site now on Firefox 45a01 dev and 44a01 nightly browsers and SSI is working as I can see my SSI included nav and sidebar content now https://centminmod.com/letsencrypt-freessl.html :)

thanks so much !
