### ISSUE TITLE
possible leak of br encoding to non supported browsers IE/Edge ?

### ISSUE THREAD

**Issue by centminmod** [google/ngx_brotli#42] opened 2016-12-06 05:34 UTC
Is it possible for ngx_brotli to incorrectly serve br encoded assets to non supported browsers like IE/Edge ? Seems I am experiencing this at https://community.centminmod.com/posts/41211/ but not sure if it's my Sucuri Cloudproxy's Nginx server in front of my ngx_brotli enabled Nginx server that is causing problems ?

> nginx -V
> nginx version: nginx/1.11.6
> built by gcc 5.2.1 20150902 (Red Hat 5.2.1-2) (GCC) 
> built with OpenSSL 1.0.2j  26 Sep 2016
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --add-module=../nginx-module-vts --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-release-1.11.33.4-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-stream_geoip_module=dynamic --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.31 --add-module=../echo-nginx-module-0.60 --add-module=../redis2-nginx-module-0.13 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.17 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.32 --with-pcre=../pcre-8.39 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../openssl-1.0.2j

**Comment by PiotrSikora** [comment] 2016-12-06 05:55
Do you have `gzip_vary on` in your config? Without it, 3rd-party proxy in front of your NGINX might be serving cached content without validating that `Accept-Encoding` matches.

**Comment by centminmod** [comment] 2016-12-06 06:24
i have the following set

```
brotli on;
brotli_static on;
brotli_min_length 1000;
brotli_buffers 32 8k;
brotli_comp_level 5;
brotli_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;
```

        gzip on;
        gzip_vary   on;
        gzip_disable "MSIE [1-6]\.";
        gzip_static on;
        gzip_min_length   1400;
        gzip_buffers      32 8k;
        gzip_http_version 1.0;
        gzip_comp_level 6;
        gzip_proxied    any;
        gzip_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;

**Comment by PiotrSikora** [comment] 2016-12-06 06:39
I don't see how this module could produce bad content encoding, especially considering that it didn't change in the past 3 months (...and the issue is presumably a new one?).

Do you have an example of request / response headers that resulted in the invalid compression?

**Comment by centminmod** [comment] 2016-12-06 07:48
IE/Edge make up less than 3% of visitors so probably hasn't been noticed much. I disabled brotli compression while I get feedback from other IE11/Edge users if that fixes the problem. I'll turn it back on afterwards and give you an example.  One of the specific assets was the css url for https://community.centminmod.com/styles/xenbase/font-awesome/css/font-awesome.min.css but it's now served via gzip while brotli is turned off.

**Comment by PiotrSikora** [comment] 2016-12-09 05:26
I'm going to close this, since there is no proof that this module is source of your issues.

**Closed by PiotrSikora** 2016-12-09 05:26 UTC

**Comment by centminmod** [comment] 2017-01-13 23:05
@PiotrSikora re-enabled ngx_brotli so it's live on my site/forums and still happening some more info

* still only happens in IE/MS Edge browsers https://community.centminmod.com/threads/site-broken-in-internet-explorer-edge.9701/
* wpt ms edge result for my forums at https://community.centminmod.com/ with screenshot https://www.webpagetest.org/result/170113_BA_1CW2/2/screen_shot/

> nginx -V
> nginx version: nginx/1.11.8
> built by gcc 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC) 
> built with OpenSSL 1.0.2j  26 Sep 2016
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --add-module=../nginx-module-vts --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-1.12.34.2-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-stream_geoip_module=dynamic --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.31 --add-module=../echo-nginx-module-0.60 --add-module=../redis2-nginx-module-0.13 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.17 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.32 --with-pcre=../pcre-8.39 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../openssl-1.0.2j

```
brotli on;
brotli_static on;
brotli_min_length 1000;
brotli_buffers 32 8k;
brotli_comp_level 5;
brotli_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;
```
and
```
        gzip on;
        gzip_vary   on;
        gzip_disable "MSIE [1-6]\.";
        gzip_static on;
        gzip_min_length   1400;
        gzip_buffers      32 8k;
        gzip_http_version 1.0;
        gzip_comp_level 6;
        gzip_proxied    any;
        gzip_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;
```

**Comment by dvershinin** [comment] 2017-02-13 17:14
@centminmod Could it be that the problem lies in rather the way new Edge's engine deals/fails with Brotli support? They seem to [have introduced support for Brotli recently](https://blogs.windows.com/msedgedev/2016/12/20/introducing-brotli-compression/#uFzHs0PI3VZAWb8F.97)
