### ISSUE TITLE
Allow for libbrotli to be compiled directly into ngx_brotli

### ISSUE THREAD

**Issue by jauderho** [google/ngx_brotli#36] opened 2016-09-10 01:06 UTC
Compiling from source. 

Would be nice if there is an option to compile libbrotli right into the ngx_brotli module which is in turn compiled into nginx.

Reason: Ubuntu 16.04 does not ship with libbrotli

**Comment by PiotrSikora** [comment] 2016-09-21 05:05
Duplicate of #31.

**Closed by PiotrSikora** 2016-09-21 05:05 UTC
